# 使用 Nginx 映像作為基礎
FROM nginx:alpine

# 複製 src 目錄下的文件到 Nginx 的服務目錄
COPY . /usr/share/nginx/html


# 預設首頁更換
RUN sed -i 's/index.html/firstPage.html/' /etc/nginx/conf.d/default.conf

# 宣告暴露的端口
EXPOSE 80

# 使用預設的 Nginx 啟動命令
CMD ["nginx", "-g", "daemon off;"]